### ISSUE TITLE
Getting an Integer out of a multiline `inner`

### ISSUE THREAD

**Issue by ldesgoui** [Hexilee/unhtml.rs#1]
Hello,

Currently, getting something like

```
  #[html(selector = "div", attr = "inner")]
  id: usize,
```

out of something like

```
<div>
    1
</div>
```

will return `Err(ParseIntError { kind: InvalidDigit })`.
Is there any way to ignore whitespace? Should I just minify the contents before using them?

Thanks

**Comment by Hexilee** [comment]
The latest version(unhtml-v0.1.2, unhtml_derive-v0.2.2) should fix it.

**Comment by ldesgoui** [comment]
Thanks
