### ISSUE TITLE
Implement `FromHtml` in terms of `from_html_ref`, not `from_html`

### ISSUE THREAD

**Issue by ErichDonGubler** [Hexilee/unhtml.rs#3]
I've been writing a bunch of hand-rolled implementations for `FromHtml`, and I often end up writing things of the form:

```rust
#[derive(Debug)]
struct Thing {

}

impl FromHtml for Thing {
    fn from_html(html: &str) -> Result<Self, Error> {
        let html = Html::parse_fragment(html);
        Self::from_html_ref(html.root_element())
    }

    fn from_html_ref(html: ElementRef) -> Result<Self, Error> {
        // Do actual work
    }
}
```

It seems that an `ElementRef` would be a more natural entry point for hand-rolling this logic, instead of dealing with a `&str`. The performance-shaped part of my brain also freaks out that the default implementation for `from_html_ref` is:

```rust
    fn from_html_ref(elem_ref: ElementRef) -> Result<Self, Error> {
        Ok(Self::from_html(&elem_ref.html())?)
    }
```

...because I already have an `ElementRef`, and the parsing is already done! Why do I need to parse this again? :(

**So, my suggestion is this: why not change `FromHtml` to have no default implementation of `from_html_ref`, and a default for `from_html`?** Something like this:

```rust

    fn from_html(html: &str) -> Result<Self, Error> {
        let html = Html::parse_fragment(html);
        Self::from_html_ref(html.root_element())
    }

    fn from_html_ref(html: ElementRef) -> Result<Self, Error>;
```

**Comment by Hexilee** [comment]
Thanks for your suggestion, actually I do like this in `VecFromHtml` :

```rust
fn from_html(selector_str: &str, html: &str) -> Result<Vec<Self::Elem>, Error> {
    Self::from_html_ref(selector_str, Html::parse_fragment(html).root_element())
}
```

However, for `FromHtml`, I implement it for all `T: FromStr`:

```rust
impl<E, T> FromHtml for T
    where E: std::error::Error + Send + Sync + 'static,
          T: FromStr<Err=E> {
    fn from_html(html: &str) -> Result<Self, Error> {
        Ok(T::from_str(html.trim())?)
    }
}
```

If I implement `from_html` by default, how should I implement `from_html_ref` for `T: FromStr`? @ErichDonGubler

**Comment by Hexilee** [comment]
A pretty solution is override implementation of `from_html`

**Comment by Hexilee** [comment]
A new version v0.3.1 is released, I will close this issue if you think it it ok.

**Comment by ErichDonGubler** [comment]
I think that leaving `from_html_ref` unimplemented and expected downstream code to implement it instead of `from_html` is reasonable. You may want to rename `from_html` and `from_html_ref` to maintain the nice naming convention you had -- i.e., renaming them to `from_html_str` and `from_html` respectively.

Otherwise, I'm not so sure that your changes being labeled 0.3.1 would be appropriate, because this could break code that previously compiled like this:

```
impl FromHtml for Thing {
    fn from_html(html: &str) -> Result<Self, Error> {
        let html = Html::parse_fragment(html);
        Self::from_html_ref(html.root_element())
    }
}
```

Cargo will automatically upgrade users of 0.3.0 to 0.3.1 because of Semantic Versionining guarantees, so this might be problematic for some users. I would suggest yanking 0.3.1 and pushing your change as 0.4.0, to minimize downstream breakages.

**Comment by Hexilee** [comment]
Yeah, you are right, v0.4.0 is released.
