### ISSUE TITLE
Parse into `Option<T>`

### ISSUE THREAD

**Issue by jhpratt** [Hexilee/unhtml.rs#4]
This could be useful for things where an element may be present and have useful info, but is sometimes expected to _not_ be present. My specific use case is ranking of sports teams — I currently have to catch the error and reparse into a different struct.

**Comment by Hexilee** [comment]
It may be useful but currently I do not have the use case and time. Maybe you can set a "flag" as default value?

**Comment by jhpratt** [comment]
@Hexilee That's certainly a possibility. Would you accept a PR if I created one? I'd certainly take a look at the code if you would!

**Comment by Hexilee** [comment]
PR is welcome! I will take some time to review the code and make the decision.

**Comment by jhpratt** [comment]
@Hexilee Looking through things now; it appears as though the only two errors that can be returned are `SourceNotFound` and `SourceEmpty`. If this is correct, would you agree that the appropriate thing to do is to cast _both_ of them to an `Option`?

If that's the correct course of action, I actually think this should be as simple as calling `.ok()` on the result, as we're disregarding both possible errors.

**Comment by Hexilee** [comment]
The purpose to use `Result` instead of `Option` is debugging more conveniently. Maybe you can use `Option` and log the err.

**Comment by Hexilee** [comment]
@jhpratt  `Option<T>` is supported in v0.7, documentation will be updated in few days, you can refer to the test [compound.rs](https://github.com/Hexilee/unhtml.rs/blob/master/src/html/compound.rs) now.

**Comment by Hexilee** [comment]
I will close this issue
